name: mlops
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.0=mkl
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2023.12.12=haa95532_0
  - expat=2.5.0=hd77b12b_0
  - icc_rt=2022.1.0=h6049295_2
  - intel-openmp=2023.1.0=h59b6b97_46320
  - libexpat=2.5.0=h63175ca_1
  - libffi=3.4.4=hd77b12b_0
  - libsqlite=3.44.2=hcfcfb64_0
  - libzlib=1.2.13=hcfcfb64_5
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py312h2bbff1b_1
  - mkl_fft=1.3.8=py312h2bbff1b_0
  - mkl_random=1.2.4=py312h59b6b97_0
  - numpy=1.26.3=py312hfd52020_0
  - numpy-base=1.26.3=py312h4dde369_0
  - openssl=3.2.0=hcfcfb64_1
  - pip=23.3.1=py312haa95532_0
  - python=3.12.1=h2628c8c_1_cpython
  - python_abi=3.12=4_cp312
  - scikit-surprise=1.1.3=py312ha90f08f_2
  - setuptools=68.2.2=py312haa95532_0
  - sqlite=3.41.2=h2bbff1b_0
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.13=h5226925_1
  - ucrt=10.0.20348.0=haa95532_0
  - vc=14.2=h21ff451_1
  - vc14_runtime=14.38.33130=h82b7239_18
  - vs2015_runtime=14.38.33130=hcb4865c_18
  - wheel=0.41.2=py312haa95532_0
  - xz=5.4.5=h8cc25b3_0
  - zlib=1.2.13=hcfcfb64_5
  - pip:
      - joblib==1.3.2
      - pandas==2.1.4
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - six==1.16.0
      - threadpoolctl==3.2.0
      - tzdata==2023.4
prefix: C:\Users\chall\anaconda3\envs\mlops
